name: Deploy Hugo Website

env:
  WC_HUGO_VERSION: '0.125.7' 

# 触发条件
on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发
  workflow_dispatch:  # 允许从 Actions 手动触发

# 权限配置
permissions:
  contents: read  # 读取代码库内容
  pages: write  # 写入 GitHub Pages
  id-token: write  # 用于身份验证

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu 运行环境
    steps:
      # 检出代码库
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录，支持 Hugo 的 .GitInfo 和 .Lastmod

      # 设置 Hugo 环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.7'  # 指定 Hugo 版本
          extended: true  # 启用 SCSS 支持

      # 构建网站
      - name: Build Hugo site
        env:
          HUGO_ENVIRONMENT: production  # 设置为生产环境
        run: |
          hugo --minify  # 直接在工作流的存储空间中生成静态文件

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
